image: debian/stable
packages: 
- git
- lua5.1
- luarocks
sources :
- https://git.sr.ht/~gpcf/advtrains

artifacts:
- advtrains.luacov.report.out
- advtrains_interlocking.luacov.report.out

tasks:

- install_mineunit : |
    for i in {busted,luacov}; do
        luarocks install --local --lua-version 5.1 $i >/dev/null
    done
    luarocks install --local --lua-version 5.1 --server=https://luarocks.org/dev mineunit
- run_unit_tests : |
    cd advtrains/serialize_lib
    ~/.luarocks/bin/busted
    for i in {advtrains,advtrains_interlocking}; do
        cd ../$i
        ~/.luarocks/bin/mineunit -c
        ~/.luarocks/bin/mineunit -r
        sed -n '/^File/,$p' luacov.report.out
        mv luacov.report.out ~/$i.luacov.report.out
    done
